In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
ds = pd.read_csv('Market_Basket.csv',)
ds

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
ds = pd.read_csv('Market_Basket.csv', header = None )
ds

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
transactions = []

for i in range(len(ds)):
    transaction = ds.iloc[i].dropna().tolist()
    transactions.append(transaction)

In [5]:
transactions[:5]

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea']]

In [6]:
!pip install apyori

Requirement already satisfied: apyori in c:\users\shamb\appdata\local\programs\python\python312\lib\site-packages (1.1.2)

In [7]:
from apyori import apriori

In [8]:

rule = apriori(transactions, min_support=0.04, min_confidence=0.002, min_length=1)
rule

In [9]:
result = list(rule)
result[:10]

[RelationRecord(items=frozenset({'burgers'}), support=0.0871883748833489, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'burgers'}), confidence=0.0871883748833489, lift=1.0)]),
 RelationRecord(items=frozenset({'cake'}), support=0.08105585921877083, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cake'}), confidence=0.08105585921877083, lift=1.0)]),
 RelationRecord(items=frozenset({'champagne'}), support=0.04679376083188908, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'champagne'}), confidence=0.04679376083188908, lift=1.0)]),
 RelationRecord(items=frozenset({'chicken'}), support=0.05999200106652446, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chicken'}), confidence=0.05999200106652446, lift=1.0)]),
 RelationRecord(items=frozenset({'chocolate'}), support=0.1638448206905746, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'chocolate'}), confidence=0.1638448206905746, lift=1.0)]),
 RelationRecord(items=frozenset({'cookies'}), support=0.08038928142914278, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cookies'}), confidence=0.08038928142914278, lift=1.0)]),
 RelationRecord(items=frozenset({'cooking oil'}), support=0.0510598586855086, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cooking oil'}), confidence=0.0510598586855086, lift=1.0)]),
 RelationRecord(items=frozenset({'eggs'}), support=0.17970937208372217, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'eggs'}), confidence=0.17970937208372217, lift=1.0)]),
 RelationRecord(items=frozenset({'escalope'}), support=0.0793227569657379, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'escalope'}), confidence=0.0793227569657379, lift=1.0)]),
 RelationRecord(items=frozenset({'french fries'}), support=0.1709105452606319, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'french fries'}), confidence=0.1709105452606319, lift=1.0)])]

In [10]:
result_list = []
for items in result:
    temp_list = []
    temp_list.append(items[0]) # Frozen-set
    temp_list.append(items[1]) # Support
    temp_list.append(items[2][0][2]) # Confidence
    temp_list.append(items[2][0][3]) # Lift

    result_list.append(temp_list)

result_df = pd.DataFrame(result_list, columns=['item', 'Support', 'Confidence', 'Lift'])

In [11]:
result_df

                            item   Support  Confidence  Lift
0                      (burgers)  0.087188    0.087188   1.0
1                         (cake)  0.081056    0.081056   1.0
2                    (champagne)  0.046794    0.046794   1.0
3                      (chicken)  0.059992    0.059992   1.0
4                    (chocolate)  0.163845    0.163845   1.0
5                      (cookies)  0.080389    0.080389   1.0
6                  (cooking oil)  0.051060    0.051060   1.0
7                         (eggs)  0.179709    0.179709   1.0
8                     (escalope)  0.079323    0.079323   1.0
9                 (french fries)  0.170911    0.170911   1.0
10                 (fresh bread)  0.043061    0.043061   1.0
11             (frozen smoothie)  0.063325    0.063325   1.0
12           (frozen vegetables)  0.095321    0.095321   1.0
13               (grated cheese)  0.052393    0.052393   1.0
14                   (green tea)  0.132116    0.132116   1.0
15                 (ground beef)  0.098254    0.098254   1.0
16               (herb & pepper)  0.049460    0.049460   1.0
17                       (honey)  0.047460    0.047460   1.0
18              (low fat yogurt)  0.076523    0.076523   1.0
19                        (milk)  0.129583    0.129583   1.0
20               (mineral water)  0.238368    0.238368   1.0
21                   (olive oil)  0.065858    0.065858   1.0
22                    (pancakes)  0.095054    0.095054   1.0
23                      (salmon)  0.042528    0.042528   1.0
24                      (shrimp)  0.071457    0.071457   1.0
25                        (soup)  0.050527    0.050527   1.0
26                   (spaghetti)  0.174110    0.174110   1.0
27                    (tomatoes)  0.068391    0.068391   1.0
28                      (turkey)  0.062525    0.062525   1.0
29            (whole wheat rice)  0.058526    0.058526   1.0
30    (chocolate, mineral water)  0.052660    0.052660   1.0
31         (eggs, mineral water)  0.050927    0.050927   1.0
32  (ground beef, mineral water)  0.040928    0.040928   1.0
33         (milk, mineral water)  0.047994    0.047994   1.0
34    (spaghetti, mineral water)  0.059725    0.059725   1.0

In [12]:
result_df.sort_values(['Confidence'],ascending=False)

                            item   Support  Confidence  Lift
20               (mineral water)  0.238368    0.238368   1.0
7                         (eggs)  0.179709    0.179709   1.0
26                   (spaghetti)  0.174110    0.174110   1.0
9                 (french fries)  0.170911    0.170911   1.0
4                    (chocolate)  0.163845    0.163845   1.0
14                   (green tea)  0.132116    0.132116   1.0
19                        (milk)  0.129583    0.129583   1.0
15                 (ground beef)  0.098254    0.098254   1.0
12           (frozen vegetables)  0.095321    0.095321   1.0
22                    (pancakes)  0.095054    0.095054   1.0
0                      (burgers)  0.087188    0.087188   1.0
1                         (cake)  0.081056    0.081056   1.0
5                      (cookies)  0.080389    0.080389   1.0
8                     (escalope)  0.079323    0.079323   1.0
18              (low fat yogurt)  0.076523    0.076523   1.0
24                      (shrimp)  0.071457    0.071457   1.0
27                    (tomatoes)  0.068391    0.068391   1.0
21                   (olive oil)  0.065858    0.065858   1.0
11             (frozen smoothie)  0.063325    0.063325   1.0
28                      (turkey)  0.062525    0.062525   1.0
3                      (chicken)  0.059992    0.059992   1.0
34    (spaghetti, mineral water)  0.059725    0.059725   1.0
29            (whole wheat rice)  0.058526    0.058526   1.0
30    (chocolate, mineral water)  0.052660    0.052660   1.0
13               (grated cheese)  0.052393    0.052393   1.0
6                  (cooking oil)  0.051060    0.051060   1.0
31         (eggs, mineral water)  0.050927    0.050927   1.0
25                        (soup)  0.050527    0.050527   1.0
16               (herb & pepper)  0.049460    0.049460   1.0
33         (milk, mineral water)  0.047994    0.047994   1.0
17                       (honey)  0.047460    0.047460   1.0
2                    (champagne)  0.046794    0.046794   1.0
10                 (fresh bread)  0.043061    0.043061   1.0
23                      (salmon)  0.042528    0.042528   1.0
32  (ground beef, mineral water)  0.040928    0.040928   1.0

In [13]:

from collections import Counter

all_items = [item for transaction in listf for item in transaction]

item_counts = Counter(all_items)

plt.figure(figsize=(20, 10))
plt.bar(item_counts.keys(), item_counts.values(), color='skyblue')
plt.xlabel('Items')
plt.ylabel('Frequency')
plt.title('Item Frequency Plot')
plt.xticks(rotation=90) 
plt.show()

NameError: name 'listf' is not defined